### ISSUE TITLE
Deployment error - related to sharp library / mozjpeg

### ISSUE THREAD

**Issue by Svarto** [stormkit-io/www-stormkit-io#69]
**Describe the bug**
I try to deploy a Gatsby website through stormkit console, but get an error during deployment.

**To Reproduce**
My repo is not public that I am working on, but looking at the error it seems like trying to deploy a website with the same dependencies as my site would provide the same error. I tried deploying with both node version 10 and 12, same error.

```
    "@apollo/client": "^3.3.6",
    "@fontsource/bubblegum-sans": "^4.1.0",
    "autoprefixer": "^10.2.0",
    "gatsby": "^2.30.1",
    "gatsby-cli": "^2.17.0",
    "gatsby-image": "^2.9.0",
    "gatsby-plugin-apollo": "^3.0.2",
    "gatsby-plugin-postcss": "^3.5.0",
    "gatsby-plugin-react-helmet": "^3.8.0",
    "gatsby-plugin-react-svg": "^3.0.0",
    "gatsby-plugin-sharp": "^2.12.0",
    "gatsby-plugin-sitemap": "^2.10.0",
    "gatsby-source-filesystem": "^2.9.0",
    "gatsby-transformer-sharp": "^2.10.0",
    "postcss": "^8.2.2",
    "prop-types": "^15.7.2",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-helmet": "^6.1.0",
    "sharp": "^0.27.0",
    "tailwindcss": "^2.0.2"
```

**Expected behavior**
Website successfully deploys.

**Error message**
```
registry: https://registry.npmjs.org/
> sharp@0.27.0 install /home/app/repo/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
> core-js@2.6.12 postinstall /home/app/repo/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"
> core-js@3.8.2 postinstall /home/app/repo/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"
> core-js-pure@3.8.2 postinstall /home/app/repo/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"
> gatsby-telemetry@1.8.0 postinstall /home/app/repo/node_modules/gatsby-telemetry
> node src/postinstall.js || true
> mozjpeg@7.0.0 postinstall /home/app/repo/node_modules/mozjpeg
> node lib/install.js
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.5/libvips-8.10.5-linuxmusl-x64.tar.br
⚠ spawn /home/app/repo/node_modules/mozjpeg/vendor/cjpeg ENOENT
⚠ mozjpeg pre-build test failed
ℹ compiling from source
✖ Error: Command failed: /bin/sh -c autoreconf -fiv
/bin/sh: autoreconf: not found
at /home/app/repo/node_modules/bin-build/node_modules/execa/index.js:231:11
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async Promise.all (index 0)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.1 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mozjpeg@7.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mozjpeg@7.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! /home/node/.npm/_logs/2021-01-07T20_10_11_055Z-debug.log
```

**Desktop (please complete the following information):**
 - OS: MacOs

**Comment by svedova** [comment]
@Svarto thanks for opening the issue! The correct place for this issue is in our app repository: https://github.com/stormkit-io/app-stormkit-io. 

I'm going to close this issue. Here's the new issue: https://github.com/stormkit-io/app-stormkit-io/issues/108
